//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORION.Admin.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestDataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestDataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Benday.Presidents.WebUi.TestData.TestDataResource", typeof(TestDataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;businessOwners&gt;
        ///  &lt;businessOwner
        ///       birthdate=&quot;2/22/1732&quot;
        ///       businessdate=&quot;12/14/1799&quot;
        ///       birthcity=&quot;Westmoreland County&quot;
        ///       birthprovince=&quot;Virginia&quot;
        ///       businesscity=&quot;Mount Vernon&quot;
        ///       businessprovince=&quot;Virginia&quot;
        ///       id=&quot;1&quot;
        ///       start=&quot;4/30/1789&quot;
        ///       end=&quot;3/4/1797&quot;
        ///       name=&quot;George Washington&quot;
        ///       firstname=&quot;George&quot;
        ///       middlename=&quot;&quot;
        ///       lastname=&quot;Washington&quot;
        ///       url=&quot;http://www.whitehouse.gov/sites/default/files/first-family/ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zaBusinessOwnersXml {
            get {
                return ResourceManager.GetString("zaBusinessOwnersXml", resourceCulture);
            }
        }
    }
}
