services:
  orion.api.userprofiles:
    image: orion.api.userprofiles
    build:
      context: .
      dockerfile: Orion.API.UserProfiles/Dockerfile

  orion.access.postgres:
    image: orion.access.postgres
    build:
      context: .
      dockerfile: Orion.Access.Postgres/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  _main__main_:
    image: _main__main_
    build:
      context: .
      dockerfile: _Main_/Dockerfile

