version: '3.9'

services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - healthnet

#  postgres:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: healthdb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: $ta99Ath0
#    ports:
#      - "5432:5432"
#    networks:
#      - healthnet
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#volumes:
#  pgdata:
#
#networks:
#  healthnet:
