version: '3.4'

services:
  
  orion.webapps.healthcheck-1:
    image: orion.webapps.healthcheck-1
    build:
      context: .
      dockerfile: src/WebApps/Orion.WebApps.HealthCheck/Dockerfile


  orion.services.stockanalyzer.api-1:
    image: orion.services.stockanalyzer.api-1
    build:
      context: .
      dockerfile: src/Services/StockAnalyzer/StockAnalyzer.API/Dockerfile
