<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\Core\Orion.Core.Basket\Orion.Core.Basket.csproj" />
      <ProjectReference Include="..\src\Core\Orion.Core.Catalog\Orion.Core.Catalog.csproj" />
      <ProjectReference Include="..\src\Core\Orion.Core.Chat\Orion.Core.Chat.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    </ItemGroup>

</Project>
