using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Orion.DataAccess.Postgres.Entities
{
    [Table("DatabaseLog")]
    [Description("Audit table tracking all DDL changes made to the OrionProductionDatabase database. Data is captured by the database trigger ddlDatabaseTriggerLog.")]
    public class DatabaseLog
    {
        [Key]
        [Column(name : "DatabaseLogID", TypeName = "int")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required(ErrorMessage = "Database Log ID is required")]
        [Display(Name = "Database Log ID")]
        [Description("Primary key for DatabaseLog records.")]
        public int? DatabaseLogID { get; set; } // int
        [Column(name : "PostTime")]
        [Required(ErrorMessage = "Post Time is required")]
        [Display(Name = "Post Time")]
        [Description("The date and time the DDL change occurred.")]
        public DateTime? PostTime { get; set; } // datetime
        [Column(name : "DatabaseUser")]
        [MaxLength(128)]
        [StringLength(128)]
        [Required(ErrorMessage = "Database User is required")]
        [Display(Name = "Database User")]
        [Description("The user who implemented the DDL change.")]
        public string DatabaseUser { get; set; } // nvarchar(128)
        [Column(name : "Event")]
        [MaxLength(128)]
        [StringLength(128)]
        [Required(ErrorMessage = "Event is required")]
        [Display(Name = "Event")]
        [Description("The type of DDL statement that was executed.")]
        public string Event { get; set; } // nvarchar(128)
        [Column(name : "Schema")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Schema")]
        [Description("The schema to which the changed object belongs.")]
        public string Schema { get; set; } // nvarchar(128)
        [Column(name : "Object")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Object")]
        [Description("The object that was changed by the DDL statment.")]
        public string Object { get; set; } // nvarchar(128)
        [Column(name : "TSQL")]
        [MaxLength]
        [Required(ErrorMessage = "TSQL is required")]
        [Display(Name = "TSQL")]
        [Description("The exact Transact-SQL statement that was executed.")]
        public string TSQL { get; set; } // nvarchar(max)
        [Column(name : "XmlEvent", TypeName = "xml")]
        [Required(ErrorMessage = "Xml Event is required")]
        [Display(Name = "Xml Event")]
        [Description("The raw XML data generated by database trigger.")]
        public string XmlEvent { get; set; } // XML(.)
    }
}
