<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Orion.Domain\Orion.Domain.csproj" />
    <ProjectReference Include="..\ORION.Domain\ORION.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Contexts\**" />
    <Compile Remove="Extensions\**" />
    <Compile Remove="Interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Contexts\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <EmbeddedResource Remove="Interfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Contexts\**" />
    <None Remove="Extensions\**" />
    <None Remove="Interfaces\**" />
  </ItemGroup>

</Project>
